CREATE TABLE CATEGORY(
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CATEGORY(NAME) VALUES ('Leisure');
INSERT INTO CATEGORY(NAME) VALUES ('Food');
INSERT INTO CATEGORY(NAME) VALUES ('Supermarket');
INSERT INTO CATEGORY(NAME) VALUES ('Drugstore');
INSERT INTO CATEGORY(NAME) VALUES ('Others');
INSERT INTO CATEGORY(NAME) VALUES ('Building');
INSERT INTO CATEGORY(NAME) VALUES ('Meat');